package com.talentica.blescanner.device;

/**
 * Created by NavalB on 24-05-2016.
 */
public enum DescriptorPermission {
	PERMISSION_READ,
	PERMISSION_READ_ENCRYPTED,
	PERMISSION_READ_ENCRYPTED_MITM,
	PERMISSION_WRITE,
	PERMISSION_WRITE_ENCRYPTED,
	PERMISSION_WRITE_ENCRYPTED_MITM,
	PERMISSION_WRITE_SIGNED,
	PERMISSION_WRITE_SIGNED_MITM;
}
